version: '3.7'

volumes:
  logs:
    driver: local

services:
  mysql:
    #    user: "root:${GID}"
    image: 'mysql:8.0'
    volumes:
      - './docker_services/mysql/data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'